-- S1.2-02 PostgreSQL-only integrity layer.
--
-- The preceding migration is generated byte-for-byte from schema.prisma.
-- This migration contains constraints that Prisma cannot fully represent:
-- partial uniqueness, cross-row/cross-table invariants, deferred assertions,
-- immutable evidence, and state-machine guards.

-- Scalar bounds and row-local conservation rules.
ALTER TABLE "CustomerSession"
  ADD CONSTRAINT "CustomerSession_refreshTokenVersion_check"
  CHECK ("refreshTokenVersion" >= 1);

ALTER TABLE "OtpChallenge"
  ADD CONSTRAINT "OtpChallenge_attempts_check"
  CHECK ("attempts" >= 0);

ALTER TABLE "AdminSession"
  ADD CONSTRAINT "AdminSession_refreshTokenVersion_check"
  CHECK ("refreshTokenVersion" >= 1);

ALTER TABLE "AdminRecoveryCode"
  ADD CONSTRAINT "AdminRecoveryCode_usedAt_check"
  CHECK ("usedAt" IS NULL OR "usedAt" >= "createdAt");

ALTER TABLE "Artist"
  ADD CONSTRAINT "Artist_artistRevenueShareBps_check"
  CHECK ("artistRevenueShareBps" BETWEEN 0 AND 10000);

ALTER TABLE "AudioContent"
  ADD CONSTRAINT "AudioContent_priceCfa_check"
  CHECK ("priceCfa" >= 0),
  ADD CONSTRAINT "AudioContent_previewSeconds_check"
  CHECK ("previewSeconds" BETWEEN 1 AND 120);

ALTER TABLE "MediaAsset"
  ADD CONSTRAINT "MediaAsset_version_check"
  CHECK ("version" >= 1),
  ADD CONSTRAINT "MediaAsset_durationSeconds_check"
  CHECK ("durationSeconds" IS NULL OR "durationSeconds" BETWEEN 1 AND 86400),
  ADD CONSTRAINT "MediaAsset_checksumSha256_check"
  CHECK ("checksumSha256" IS NULL OR "checksumSha256" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "MediaAsset_providerReferences_check"
  CHECK (
    ("privateProviderUploadRef" IS NULL AND "privateProviderAssetRef" IS NULL)
    OR "provider" IS NOT NULL
  );

ALTER TABLE "MediaWebhookInbox"
  ADD CONSTRAINT "MediaWebhookInbox_processingCompletion_check"
  CHECK (
    ("processingStatus" IN ('RECEIVED', 'PROCESSING') AND "processedAt" IS NULL)
    OR ("processingStatus" IN ('PROCESSED', 'REJECTED') AND "processedAt" IS NOT NULL)
  ),
  ADD CONSTRAINT "MediaWebhookInbox_payloadHash_check"
  CHECK ("payloadHash" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "MediaWebhookInbox_timestamps_check"
  CHECK (
    "signatureVerifiedAt" <= "receivedAt"
    AND ("processedAt" IS NULL OR "processedAt" >= "receivedAt")
  );

ALTER TABLE "ContentPublication"
  ADD CONSTRAINT "ContentPublication_archivedAt_check"
  CHECK ("archivedAt" IS NULL OR "archivedAt" >= "publishedAt");

ALTER TABLE "PublicationMediaAsset"
  ADD CONSTRAINT "PublicationMediaAsset_version_check"
  CHECK ("mediaAssetVersion" >= 1),
  ADD CONSTRAINT "PublicationMediaAsset_checksum_check"
  CHECK ("readinessChecksum" ~ '^[0-9a-f]{64}$');

ALTER TABLE "Order"
  ADD CONSTRAINT "Order_totalCfa_check"
  CHECK ("totalCfa" >= 0);

ALTER TABLE "OrderItem"
  ADD CONSTRAINT "OrderItem_unitPriceCfa_check"
  CHECK ("unitPriceCfa" >= 0),
  ADD CONSTRAINT "OrderItem_quantity_check"
  CHECK ("quantity" >= 1);

ALTER TABLE "OrderStateEvent"
  ADD CONSTRAINT "OrderStateEvent_sequence_check"
  CHECK ("sequence" >= 1);

ALTER TABLE "PaymentAttempt"
  ADD CONSTRAINT "PaymentAttempt_amountCfa_check"
  CHECK ("amountCfa" >= 0),
  ADD CONSTRAINT "PaymentAttempt_idempotencyKey_check"
  CHECK (length("idempotencyKey") BETWEEN 16 AND 128),
  ADD CONSTRAINT "PaymentAttempt_providerReference_check"
  CHECK ("providerReference" IS NULL OR length("providerReference") > 0);

ALTER TABLE "PaymentAttemptEvent"
  ADD CONSTRAINT "PaymentAttemptEvent_sequence_check"
  CHECK ("sequence" >= 1);

ALTER TABLE "PaymentWebhookInbox"
  ADD CONSTRAINT "PaymentWebhookInbox_processingCompletion_check"
  CHECK (
    ("processingStatus" IN ('RECEIVED', 'PROCESSING') AND "processedAt" IS NULL)
    OR ("processingStatus" IN ('PROCESSED', 'REJECTED') AND "processedAt" IS NOT NULL)
  ),
  ADD CONSTRAINT "PaymentWebhookInbox_payloadHash_check"
  CHECK ("payloadHash" ~ '^[0-9a-f]{64}$'),
  ADD CONSTRAINT "PaymentWebhookInbox_timestamps_check"
  CHECK (
    "signatureVerifiedAt" <= "receivedAt"
    AND ("processedAt" IS NULL OR "processedAt" >= "receivedAt")
  );

ALTER TABLE "Settlement"
  ADD CONSTRAINT "Settlement_amounts_check"
  CHECK (
    "settledAmountCfa" >= 0
    AND "distributableBasisCfa" >= 0
    AND "artistPayableAmountCfa" >= 0
    AND "platformAmountCfa" >= 0
    AND "distributableBasisCfa" <= "settledAmountCfa"
    AND "artistPayableAmountCfa" + "platformAmountCfa" = "distributableBasisCfa"
  );

ALTER TABLE "ArtistSettlement"
  ADD CONSTRAINT "ArtistSettlement_sequence_check"
  CHECK ("settlementSequence" >= 1),
  ADD CONSTRAINT "ArtistSettlement_carry_check"
  CHECK (
    "carryInNumerator" BETWEEN 0 AND 9999
    AND "carryOutNumerator" BETWEEN 0 AND 9999
  ),
  ADD CONSTRAINT "ArtistSettlement_numerators_check"
  CHECK (
    "exactEarningsNumerator" >= 0
    AND "exactNumerator" >= 0
    AND "payableAmountCfa" >= 0
    AND "exactNumerator" = "carryInNumerator"::BIGINT + "exactEarningsNumerator"
    AND "payableAmountCfa"::BIGINT = "exactNumerator" / 10000
    AND "carryOutNumerator"::BIGINT = "exactNumerator" % 10000
  );

ALTER TABLE "LedgerTransactionGroup"
  ADD CONSTRAINT "LedgerTransactionGroup_correction_check"
  CHECK ("correctionOfGroupId" IS NULL OR "correctionOfGroupId" <> "id");

ALTER TABLE "LedgerPosting"
  ADD CONSTRAINT "LedgerPosting_amountCfa_check"
  CHECK ("amountCfa" > 0);

ALTER TABLE "ArtistEarning"
  ADD CONSTRAINT "ArtistEarning_amounts_check"
  CHECK (
    "grossItemAmountCfa" >= 0
    AND "legallyRequiredTaxCfa" >= 0
    AND "refundAdjustmentCfa" >= 0
    AND "frozenBasisCfa" >= 0
    AND "legallyRequiredTaxCfa" + "refundAdjustmentCfa" <= "grossItemAmountCfa"
    AND "frozenBasisCfa" = "grossItemAmountCfa" - "legallyRequiredTaxCfa" - "refundAdjustmentCfa"
  ),
  ADD CONSTRAINT "ArtistEarning_rateAndNumerator_check"
  CHECK (
    "artistRevenueShareBps" BETWEEN 0 AND 10000
    AND "exactEarningNumerator" >= 0
    AND "exactEarningNumerator" = "frozenBasisCfa"::BIGINT * "artistRevenueShareBps"::BIGINT
  );

ALTER TABLE "PreviewGrant"
  ADD CONSTRAINT "PreviewGrant_maxDurationSeconds_check"
  CHECK ("maxDurationSeconds" BETWEEN 1 AND 120),
  ADD CONSTRAINT "PreviewGrant_expiry_check"
  CHECK ("expiresAt" > "createdAt");

ALTER TABLE "PreviewPlaybackDescriptor"
  ADD CONSTRAINT "PreviewPlaybackDescriptor_expiry_check"
  CHECK ("expiresAt" > "issuedAt" AND "expiresAt" <= "issuedAt" + INTERVAL '300 seconds');

ALTER TABLE "PurchasedPlaybackDescriptor"
  ADD CONSTRAINT "PurchasedPlaybackDescriptor_expiry_check"
  CHECK ("expiresAt" > "issuedAt" AND "expiresAt" <= "issuedAt" + INTERVAL '300 seconds');

ALTER TABLE "IdempotencyRecord"
  ADD CONSTRAINT "IdempotencyRecord_key_check"
  CHECK (length("idempotencyKey") BETWEEN 16 AND 128),
  ADD CONSTRAINT "IdempotencyRecord_responseCode_check"
  CHECK ("responseCode" BETWEEN 100 AND 599);

ALTER TABLE "AdminIdempotencyRecord"
  ADD CONSTRAINT "AdminIdempotencyRecord_key_check"
  CHECK (length("idempotencyKey") BETWEEN 16 AND 128),
  ADD CONSTRAINT "AdminIdempotencyRecord_responseCode_check"
  CHECK ("responseCode" BETWEEN 100 AND 599);

ALTER TABLE "AuditLog"
  ADD CONSTRAINT "AuditLog_requiredText_check"
  CHECK (
    length("action") > 0
    AND length("entityType") > 0
    AND length("entityId") > 0
    AND length("reason") > 0
    AND length("requestId") BETWEEN 8 AND 128
  );

ALTER TABLE "OutboxEvent"
  ADD CONSTRAINT "OutboxEvent_publishedAt_check"
  CHECK ("publishedAt" IS NULL OR "publishedAt" >= "createdAt");

ALTER TABLE "Entitlement"
  ADD CONSTRAINT "Entitlement_revokedAt_check"
  CHECK ("revokedAt" IS NULL OR "revokedAt" >= "grantedAt");

-- Partial and provider-scoped uniqueness.
CREATE UNIQUE INDEX "CustomerSession_one_active_per_customer_key"
  ON "CustomerSession" ("customerId")
  WHERE "revokedAt" IS NULL;

CREATE UNIQUE INDEX "ContentPublication_one_active_per_content_key"
  ON "ContentPublication" ("audioContentId")
  WHERE "archivedAt" IS NULL;

CREATE UNIQUE INDEX "PaymentAttempt_id_provider_key"
  ON "PaymentAttempt" ("id", "provider");

CREATE UNIQUE INDEX "MediaAsset_id_provider_key"
  ON "MediaAsset" ("id", "provider");

ALTER TABLE "PaymentWebhookInbox"
  ADD CONSTRAINT "PaymentWebhookInbox_attempt_provider_fkey"
  FOREIGN KEY ("paymentAttemptId", "provider")
  REFERENCES "PaymentAttempt" ("id", "provider")
  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE "MediaWebhookInbox"
  ADD CONSTRAINT "MediaWebhookInbox_asset_provider_fkey"
  FOREIGN KEY ("mediaAssetId", "provider")
  REFERENCES "MediaAsset" ("id", "provider")
  ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Generic append-only enforcement for immutable evidence rows.
CREATE FUNCTION public.kora_reject_row_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  RAISE EXCEPTION USING
    ERRCODE = '23514',
    MESSAGE = format('%I is append-only; %s is forbidden', TG_TABLE_NAME, TG_OP);
END;
$$;

CREATE TRIGGER "Order_immutable"
  BEFORE UPDATE OR DELETE ON "Order"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "OrderItem_immutable"
  BEFORE UPDATE OR DELETE ON "OrderItem"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "OrderStateEvent_append_only"
  BEFORE UPDATE OR DELETE ON "OrderStateEvent"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "PaymentAttemptEvent_append_only"
  BEFORE UPDATE OR DELETE ON "PaymentAttemptEvent"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "Settlement_append_only"
  BEFORE UPDATE OR DELETE ON "Settlement"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "ArtistSettlement_append_only"
  BEFORE UPDATE OR DELETE ON "ArtistSettlement"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "LedgerAccount_immutable"
  BEFORE UPDATE OR DELETE ON "LedgerAccount"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "LedgerTransactionGroup_append_only"
  BEFORE UPDATE OR DELETE ON "LedgerTransactionGroup"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "LedgerPosting_append_only"
  BEFORE UPDATE OR DELETE ON "LedgerPosting"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "ArtistEarning_append_only"
  BEFORE UPDATE OR DELETE ON "ArtistEarning"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "PublicationMediaAsset_append_only"
  BEFORE UPDATE OR DELETE ON "PublicationMediaAsset"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();
CREATE TRIGGER "AuditLog_append_only"
  BEFORE UPDATE OR DELETE ON "AuditLog"
  FOR EACH ROW EXECUTE FUNCTION public.kora_reject_row_mutation();

-- Recovery-code identity and hash never change. Consumption is a one-way
-- marker; set rotation/deletion remains a future authenticated transaction.
CREATE FUNCTION public.kora_guard_admin_recovery_code()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW."usedAt" IS NOT NULL THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'AdminRecoveryCode must be inserted unused';
    END IF;
    RETURN NEW;
  END IF;

  IF ROW(NEW."id", NEW."adminUserId", NEW."codeHash", NEW."createdAt")
     IS DISTINCT FROM
     ROW(OLD."id", OLD."adminUserId", OLD."codeHash", OLD."createdAt")
     OR (OLD."usedAt" IS NOT NULL AND NEW."usedAt" IS DISTINCT FROM OLD."usedAt") THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'AdminRecoveryCode hash and consumption proof are immutable';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "AdminRecoveryCode_durable_consumption"
  BEFORE INSERT OR UPDATE ON "AdminRecoveryCode"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_admin_recovery_code();

-- Immutable server-assigned admin provenance.
CREATE FUNCTION public.kora_guard_catalog_provenance()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NEW."createdByAdminId" IS DISTINCT FROM OLD."createdByAdminId" THEN
    RAISE EXCEPTION USING
      ERRCODE = '23514',
      MESSAGE = format('%I.createdByAdminId is immutable', TG_TABLE_NAME);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "Artist_admin_provenance_immutable"
  BEFORE UPDATE OF "createdByAdminId" ON "Artist"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_catalog_provenance();
CREATE TRIGGER "AudioContent_admin_provenance_immutable"
  BEFORE UPDATE OF "createdByAdminId" ON "AudioContent"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_catalog_provenance();

-- Publication rows preserve their creator and proof. Only one monotonic
-- archival timestamp may be assigned; deletion and all other rewrites fail.
CREATE FUNCTION public.kora_guard_content_publication()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ContentPublication is append-only; DELETE is forbidden';
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW."archivedAt" IS NOT NULL THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ContentPublication must be inserted active';
    END IF;
    RETURN NEW;
  END IF;

  IF ROW(NEW."id", NEW."audioContentId", NEW."publishedByAdminId", NEW."publishedAt")
     IS DISTINCT FROM
     ROW(OLD."id", OLD."audioContentId", OLD."publishedByAdminId", OLD."publishedAt") THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ContentPublication proof and admin provenance are immutable';
  END IF;

  IF NEW."archivedAt" IS DISTINCT FROM OLD."archivedAt"
     AND NOT (OLD."archivedAt" IS NULL AND NEW."archivedAt" IS NOT NULL) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ContentPublication.archivedAt may only be assigned once';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER "ContentPublication_append_only"
  BEFORE INSERT OR UPDATE OR DELETE ON "ContentPublication"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_content_publication();

-- Payment attempts are immutable except for the one-time provider reference.
CREATE FUNCTION public.kora_guard_payment_attempt()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentAttempt is immutable; DELETE is forbidden';
  END IF;

  IF ROW(NEW."id", NEW."orderId", NEW."provider", NEW."amountCfa", NEW."currency", NEW."idempotencyKey", NEW."createdAt")
     IS DISTINCT FROM
     ROW(OLD."id", OLD."orderId", OLD."provider", OLD."amountCfa", OLD."currency", OLD."idempotencyKey", OLD."createdAt") THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentAttempt immutable fields cannot be rewritten';
  END IF;

  IF OLD."providerReference" IS NOT NULL
     AND NEW."providerReference" IS DISTINCT FROM OLD."providerReference" THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentAttempt.providerReference may only be assigned once';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER "PaymentAttempt_immutable"
  BEFORE UPDATE OR DELETE ON "PaymentAttempt"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_payment_attempt();

-- Media lifecycle and provider identifiers are server-controlled. Provider
-- identifiers and the provider itself cannot be reassigned after attribution.
CREATE FUNCTION public.kora_guard_media_asset()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaAsset evidence cannot be deleted';
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW."processingStatus" <> 'PREPARING' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaAsset must start in PREPARING';
    END IF;
    RETURN NEW;
  END IF;

  IF ROW(NEW."id", NEW."audioContentId", NEW."kind", NEW."version", NEW."createdAt")
     IS DISTINCT FROM ROW(OLD."id", OLD."audioContentId", OLD."kind", OLD."version", OLD."createdAt") THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaAsset identity and version are immutable';
  END IF;

  IF OLD."privateProviderUploadRef" IS NOT NULL
     AND NEW."privateProviderUploadRef" IS DISTINCT FROM OLD."privateProviderUploadRef" THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaAsset.privateProviderUploadRef may only be assigned once';
  END IF;
  IF OLD."privateProviderAssetRef" IS NOT NULL
     AND NEW."privateProviderAssetRef" IS DISTINCT FROM OLD."privateProviderAssetRef" THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaAsset.privateProviderAssetRef may only be assigned once';
  END IF;
  IF OLD."provider" IS NOT NULL
     AND NEW."provider" IS DISTINCT FROM OLD."provider" THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaAsset.provider is immutable after attribution';
  END IF;

  IF NEW."processingStatus" IS DISTINCT FROM OLD."processingStatus"
     AND NOT (CASE OLD."processingStatus"
       WHEN 'PREPARING' THEN NEW."processingStatus" IN ('UPLOAD_PENDING', 'FAILED')
       WHEN 'UPLOAD_PENDING' THEN NEW."processingStatus" IN ('PROCESSING', 'FAILED')
       WHEN 'PROCESSING' THEN NEW."processingStatus" IN ('READY', 'FAILED')
       ELSE FALSE
     END) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid MediaAsset processing-state transition';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER "MediaAsset_lifecycle_and_references"
  BEFORE INSERT OR UPDATE OR DELETE ON "MediaAsset"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_media_asset();

-- Inbox rows are durable. Only their processing status and completion marker
-- can advance along the contracted state machine.
CREATE FUNCTION public.kora_guard_payment_inbox()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentWebhookInbox is durable; DELETE is forbidden';
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF NEW."processingStatus" <> 'RECEIVED' OR NEW."processedAt" IS NOT NULL THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentWebhookInbox must start in RECEIVED';
    END IF;
  ELSE
    IF ROW(NEW."id", NEW."provider", NEW."providerEventKey", NEW."paymentAttemptId", NEW."payloadHash", NEW."encryptedPayload", NEW."signatureVerifiedAt", NEW."receivedAt")
       IS DISTINCT FROM
       ROW(OLD."id", OLD."provider", OLD."providerEventKey", OLD."paymentAttemptId", OLD."payloadHash", OLD."encryptedPayload", OLD."signatureVerifiedAt", OLD."receivedAt") THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentWebhookInbox evidence is immutable';
    END IF;
    IF OLD."processedAt" IS NOT NULL
       AND NEW."processedAt" IS DISTINCT FROM OLD."processedAt" THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentWebhookInbox.processedAt may only be assigned once';
    END IF;
    IF NEW."processingStatus" IS DISTINCT FROM OLD."processingStatus"
       AND NOT (CASE OLD."processingStatus"
         WHEN 'RECEIVED' THEN NEW."processingStatus" IN ('PROCESSING', 'REJECTED')
         WHEN 'PROCESSING' THEN NEW."processingStatus" IN ('PROCESSED', 'REJECTED')
         ELSE FALSE
       END) THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid PaymentWebhookInbox state transition';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "PaymentWebhookInbox_durable_state"
  BEFORE INSERT OR UPDATE OR DELETE ON "PaymentWebhookInbox"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_payment_inbox();

CREATE FUNCTION public.kora_guard_media_inbox()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaWebhookInbox is durable; DELETE is forbidden';
  END IF;
  IF TG_OP = 'INSERT' THEN
    IF NEW."processingStatus" <> 'RECEIVED' OR NEW."processedAt" IS NOT NULL THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaWebhookInbox must start in RECEIVED';
    END IF;
  ELSE
    IF ROW(NEW."id", NEW."provider", NEW."providerEventKey", NEW."mediaAssetId", NEW."eventType", NEW."payloadHash", NEW."encryptedPayload", NEW."signatureVerifiedAt", NEW."receivedAt")
       IS DISTINCT FROM
       ROW(OLD."id", OLD."provider", OLD."providerEventKey", OLD."mediaAssetId", OLD."eventType", OLD."payloadHash", OLD."encryptedPayload", OLD."signatureVerifiedAt", OLD."receivedAt") THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaWebhookInbox evidence is immutable';
    END IF;
    IF OLD."processedAt" IS NOT NULL
       AND NEW."processedAt" IS DISTINCT FROM OLD."processedAt" THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'MediaWebhookInbox.processedAt may only be assigned once';
    END IF;
    IF NEW."processingStatus" IS DISTINCT FROM OLD."processingStatus"
       AND NOT (CASE OLD."processingStatus"
         WHEN 'RECEIVED' THEN NEW."processingStatus" IN ('PROCESSING', 'REJECTED')
         WHEN 'PROCESSING' THEN NEW."processingStatus" IN ('PROCESSED', 'REJECTED')
         ELSE FALSE
       END) THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid MediaWebhookInbox state transition';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "MediaWebhookInbox_durable_state"
  BEFORE INSERT OR UPDATE OR DELETE ON "MediaWebhookInbox"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_media_inbox();

-- Outbox publication and entitlement revocation are monotonic markers.
CREATE FUNCTION public.kora_guard_outbox_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'OutboxEvent is durable; DELETE is forbidden';
  END IF;
  IF TG_OP = 'INSERT' AND NEW."publishedAt" IS NOT NULL THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'OutboxEvent must be inserted unpublished';
  END IF;
  IF TG_OP = 'UPDATE' THEN
    IF ROW(NEW."id", NEW."aggregateType", NEW."aggregateId", NEW."eventType", NEW."deduplicationKey", NEW."payload", NEW."createdAt")
       IS DISTINCT FROM
       ROW(OLD."id", OLD."aggregateType", OLD."aggregateId", OLD."eventType", OLD."deduplicationKey", OLD."payload", OLD."createdAt")
       OR (OLD."publishedAt" IS NOT NULL AND NEW."publishedAt" IS DISTINCT FROM OLD."publishedAt") THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'OutboxEvent evidence is immutable';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "OutboxEvent_durable"
  BEFORE INSERT OR UPDATE OR DELETE ON "OutboxEvent"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_outbox_event();

CREATE FUNCTION public.kora_guard_entitlement()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Entitlement evidence cannot be deleted';
  END IF;
  IF ROW(NEW."id", NEW."customerId", NEW."audioContentId", NEW."orderItemId", NEW."settlementId", NEW."orderId", NEW."source", NEW."grantedAt")
     IS DISTINCT FROM
     ROW(OLD."id", OLD."customerId", OLD."audioContentId", OLD."orderItemId", OLD."settlementId", OLD."orderId", OLD."source", OLD."grantedAt")
     OR (OLD."revokedAt" IS NOT NULL AND NEW."revokedAt" IS DISTINCT FROM OLD."revokedAt") THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Entitlement grant evidence is immutable';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "Entitlement_durable"
  BEFORE UPDATE OR DELETE ON "Entitlement"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_entitlement();

-- An Order is assembled before its first state event. Once lifecycle evidence
-- exists, no additional priced or zero-valued item may reopen the snapshot.
CREATE FUNCTION public.kora_guard_order_item_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM 1 FROM public."Order" WHERE "id" = NEW."orderId" FOR UPDATE;
  IF FOUND AND (
    EXISTS (SELECT 1 FROM public."OrderStateEvent" WHERE "orderId" = NEW."orderId")
    OR EXISTS (SELECT 1 FROM public."PaymentAttempt" WHERE "orderId" = NEW."orderId")
    OR EXISTS (SELECT 1 FROM public."Settlement" WHERE "orderId" = NEW."orderId")
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'OrderItem cannot be appended after Order lifecycle has started';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "OrderItem_insert_before_lifecycle"
  BEFORE INSERT ON "OrderItem"
  FOR EACH ROW EXECUTE FUNCTION public.kora_guard_order_item_insert();

CREATE FUNCTION public.kora_assert_order_history(order_id TEXT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public."Order" WHERE "id" = order_id)
     AND NOT EXISTS (SELECT 1 FROM public."OrderStateEvent" WHERE "orderId" = order_id) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Order requires state history in its creation transaction';
  END IF;
END;
$$;

CREATE FUNCTION public.kora_check_order_history_from_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM public.kora_assert_order_history(NEW."id");
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "Order_requires_history"
  AFTER INSERT ON "Order"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_order_history_from_row();

-- Append-only state events must be gapless, ordered, and follow the exact
-- contracted transitions. Locking the parent serializes concurrent appends.
CREATE FUNCTION public.kora_validate_order_state_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  previous_sequence INTEGER;
  previous_state "OrderState";
  previous_recorded_at TIMESTAMP(3);
BEGIN
  PERFORM 1 FROM public."Order" WHERE "id" = NEW."orderId" FOR UPDATE;
  SELECT "sequence", "state", "recordedAt"
    INTO previous_sequence, previous_state, previous_recorded_at
    FROM public."OrderStateEvent"
    WHERE "orderId" = NEW."orderId"
    ORDER BY "sequence" DESC
    LIMIT 1;

  IF NOT FOUND THEN
    IF NEW."sequence" <> 1 OR NEW."state" <> 'CREATED' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Order state history must start at sequence 1 in CREATED';
    END IF;
  ELSIF NEW."sequence" <> previous_sequence + 1
     OR NEW."recordedAt" < previous_recorded_at
     OR NOT (CASE previous_state
       WHEN 'CREATED' THEN NEW."state" IN ('PAYMENT_PENDING', 'CANCELLED')
       WHEN 'PAYMENT_PENDING' THEN NEW."state" IN ('SETTLED', 'CANCELLED')
       ELSE FALSE
     END) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid Order state sequence or transition';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "OrderStateEvent_sequence_and_transition"
  BEFORE INSERT ON "OrderStateEvent"
  FOR EACH ROW EXECUTE FUNCTION public.kora_validate_order_state_event();

CREATE FUNCTION public.kora_validate_payment_attempt_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  previous_sequence INTEGER;
  previous_state "PaymentAttemptState";
  previous_recorded_at TIMESTAMP(3);
BEGIN
  PERFORM 1 FROM public."PaymentAttempt" WHERE "id" = NEW."paymentAttemptId" FOR UPDATE;
  SELECT "sequence", "state", "recordedAt"
    INTO previous_sequence, previous_state, previous_recorded_at
    FROM public."PaymentAttemptEvent"
    WHERE "paymentAttemptId" = NEW."paymentAttemptId"
    ORDER BY "sequence" DESC
    LIMIT 1;

  IF NOT FOUND THEN
    IF NEW."sequence" <> 1 OR NEW."state" <> 'CREATED' THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentAttempt history must start at sequence 1 in CREATED';
    END IF;
  ELSIF NEW."sequence" <> previous_sequence + 1
     OR NEW."recordedAt" < previous_recorded_at
     OR NOT (CASE previous_state
       WHEN 'CREATED' THEN NEW."state" IN ('PENDING', 'CANCELLED')
       WHEN 'PENDING' THEN NEW."state" IN ('SUCCEEDED', 'FAILED', 'CANCELLED', 'EXPIRED')
       ELSE FALSE
     END) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'invalid PaymentAttempt state sequence or transition';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "PaymentAttemptEvent_sequence_and_transition"
  BEFORE INSERT ON "PaymentAttemptEvent"
  FOR EACH ROW EXECUTE FUNCTION public.kora_validate_payment_attempt_event();

-- Attempts must start their own history in the creation transaction and may
-- only be created while their Order is payment-pending. An already-settled
-- Order only remains associated with the exact attempt used by its Settlement.
CREATE FUNCTION public.kora_assert_payment_attempt_history_and_order_state(payment_attempt_id TEXT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  target_order_id TEXT;
  latest_order_state "OrderState";
BEGIN
  SELECT "orderId" INTO target_order_id
    FROM public."PaymentAttempt" WHERE "id" = payment_attempt_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public."PaymentAttemptEvent" WHERE "paymentAttemptId" = payment_attempt_id
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentAttempt requires state history in its creation transaction';
  END IF;

  SELECT "state" INTO latest_order_state
    FROM public."OrderStateEvent"
    WHERE "orderId" = target_order_id
    ORDER BY "sequence" DESC
    LIMIT 1;

  IF latest_order_state IS DISTINCT FROM 'PAYMENT_PENDING'
     AND NOT (
       latest_order_state IS NOT DISTINCT FROM 'SETTLED'
       AND EXISTS (
         SELECT 1 FROM public."Settlement"
         WHERE "orderId" = target_order_id AND "paymentAttemptId" = payment_attempt_id
       )
     ) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentAttempt must be created for a payment-pending Order';
  END IF;
END;
$$;

CREATE FUNCTION public.kora_check_payment_attempt_history_from_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM public.kora_assert_payment_attempt_history_and_order_state(NEW."id");
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "PaymentAttempt_requires_history_and_order_state"
  AFTER INSERT ON "PaymentAttempt"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_payment_attempt_history_from_row();

-- Orders are immutable priced snapshots. The deferred assertion permits the
-- order and all of its items to be inserted in one transaction.
CREATE FUNCTION public.kora_assert_order_total()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  target_order_id TEXT;
  expected_total BIGINT;
  actual_total INTEGER;
  item_count BIGINT;
BEGIN
  target_order_id := to_jsonb(NEW) ->> CASE WHEN TG_TABLE_NAME = 'Order' THEN 'id' ELSE 'orderId' END;
  SELECT o."totalCfa", COUNT(i."id"), COALESCE(SUM(i."unitPriceCfa"::BIGINT * i."quantity"::BIGINT), 0)
    INTO actual_total, item_count, expected_total
    FROM public."Order" o
    LEFT JOIN public."OrderItem" i ON i."orderId" = o."id"
    WHERE o."id" = target_order_id
    GROUP BY o."totalCfa";

  IF FOUND AND (item_count = 0 OR actual_total::BIGINT <> expected_total) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Order total must equal its immutable priced items';
  END IF;
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "Order_total_matches_items"
  AFTER INSERT ON "Order"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_assert_order_total();
CREATE CONSTRAINT TRIGGER "OrderItem_total_matches_order"
  AFTER INSERT ON "OrderItem"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_assert_order_total();

-- Attempts and settlements remain tied to the immutable order amount. A
-- settlement also proves that the referenced event is the latest SUCCEEDED
-- event for the same attempt and order.
CREATE FUNCTION public.kora_validate_payment_attempt_amount()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  order_total INTEGER;
  order_currency "Currency";
BEGIN
  SELECT "totalCfa", "currency" INTO order_total, order_currency
    FROM public."Order" WHERE "id" = NEW."orderId" FOR UPDATE;
  IF FOUND AND (NEW."amountCfa" <> order_total OR NEW."currency" <> order_currency) THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'PaymentAttempt amount and currency must match Order';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "PaymentAttempt_matches_order"
  BEFORE INSERT ON "PaymentAttempt"
  FOR EACH ROW EXECUTE FUNCTION public.kora_validate_payment_attempt_amount();

CREATE FUNCTION public.kora_validate_settlement()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  order_total INTEGER;
  order_currency "Currency";
  attempt_amount INTEGER;
  attempt_currency "Currency";
  event_state "PaymentAttemptState";
  event_sequence INTEGER;
  latest_sequence INTEGER;
BEGIN
  SELECT o."totalCfa", o."currency", p."amountCfa", p."currency", e."state", e."sequence"
    INTO order_total, order_currency, attempt_amount, attempt_currency, event_state, event_sequence
    FROM public."Order" o
    JOIN public."PaymentAttempt" p ON p."id" = NEW."paymentAttemptId" AND p."orderId" = o."id"
    JOIN public."PaymentAttemptEvent" e ON e."id" = NEW."succeededAttemptEventId" AND e."paymentAttemptId" = p."id"
    WHERE o."id" = NEW."orderId"
    FOR UPDATE OF o, p, e;

  SELECT MAX("sequence") INTO latest_sequence
    FROM public."PaymentAttemptEvent"
    WHERE "paymentAttemptId" = NEW."paymentAttemptId";

  IF order_total IS NULL
     OR event_state IS DISTINCT FROM 'SUCCEEDED'
     OR event_sequence <> latest_sequence
     OR NEW."settledAmountCfa" <> order_total
     OR NEW."settledAmountCfa" <> attempt_amount
     OR order_currency <> 'XOF'
     OR attempt_currency <> order_currency THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Settlement must match the latest SUCCEEDED attempt event and immutable Order amount';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "Settlement_succeeded_attempt_guard"
  BEFORE INSERT ON "Settlement"
  FOR EACH ROW EXECUTE FUNCTION public.kora_validate_settlement();

-- Settlement and the terminal Order state are a bidirectional deferred fact:
-- neither side may commit without the other, regardless of insertion order.
CREATE FUNCTION public.kora_assert_order_settlement_state(order_id TEXT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  latest_order_state "OrderState";
  has_settlement BOOLEAN;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public."Order" WHERE "id" = order_id) THEN
    RETURN;
  END IF;

  SELECT "state" INTO latest_order_state
    FROM public."OrderStateEvent"
    WHERE "orderId" = order_id
    ORDER BY "sequence" DESC
    LIMIT 1;
  SELECT EXISTS (
    SELECT 1 FROM public."Settlement" WHERE "orderId" = order_id
  ) INTO has_settlement;

  IF has_settlement IS DISTINCT FROM (latest_order_state IS NOT DISTINCT FROM 'SETTLED') THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Settlement and latest Order state SETTLED must be committed together';
  END IF;
END;
$$;

CREATE FUNCTION public.kora_check_order_settlement_state_from_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM public.kora_assert_order_settlement_state(NEW."orderId");
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "Settlement_requires_settled_order"
  AFTER INSERT ON "Settlement"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_order_settlement_state_from_row();
CREATE CONSTRAINT TRIGGER "OrderStateEvent_settlement_consistency"
  AFTER INSERT ON "OrderStateEvent"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_order_settlement_state_from_row();

-- Carry consumption is serialized by locking the immediate predecessor. The
-- composite FK and unique keys additionally enforce same-artist/single-use.
CREATE FUNCTION public.kora_validate_artist_settlement_predecessor()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  predecessor_sequence BIGINT;
  predecessor_carry INTEGER;
  settlement_policy "ArtistEarningAllocationPolicy";
  settlement_reconciled_at TIMESTAMP(3);
BEGIN
  SELECT "artistAllocationPolicy", "reconciledAt"
    INTO settlement_policy, settlement_reconciled_at
    FROM public."Settlement"
    WHERE "id" = NEW."settlementId" AND "orderId" = NEW."orderId"
    FOR UPDATE;

  IF settlement_policy IS NULL
     OR NEW."allocationPolicy" <> settlement_policy
     OR NEW."reconciledAt" <> settlement_reconciled_at THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ArtistSettlement policy and reconciliation must match Settlement';
  END IF;

  IF NEW."settlementSequence" = 1 THEN
    IF NEW."previousArtistSettlementId" IS NOT NULL OR NEW."carryInNumerator" <> 0 THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'first ArtistSettlement must have no predecessor and zero carry';
    END IF;
  ELSE
    IF NEW."previousArtistSettlementId" IS NULL THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ArtistSettlement requires its immediate predecessor';
    END IF;
    SELECT "settlementSequence", "carryOutNumerator"
      INTO predecessor_sequence, predecessor_carry
      FROM public."ArtistSettlement"
      WHERE "id" = NEW."previousArtistSettlementId" AND "artistId" = NEW."artistId"
      FOR UPDATE;
    IF NOT FOUND
       OR predecessor_sequence + 1 <> NEW."settlementSequence"
       OR predecessor_carry <> NEW."carryInNumerator" THEN
      RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ArtistSettlement must consume the immediate same-artist carry exactly';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "ArtistSettlement_predecessor_guard"
  BEFORE INSERT ON "ArtistSettlement"
  FOR EACH ROW EXECUTE FUNCTION public.kora_validate_artist_settlement_predecessor();

-- Publication readiness is a deferred cross-table assertion so the immutable
-- publication and its two immutable links can be inserted in one transaction.
CREATE FUNCTION public.kora_assert_publication_ready(publication_id TEXT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  link_count BIGINT;
  audio_count BIGINT;
  cover_count BIGINT;
  ready_count BIGINT;
  publication_time TIMESTAMP(3);
BEGIN
  SELECT "publishedAt" INTO publication_time
    FROM public."ContentPublication" WHERE "id" = publication_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT COUNT(*),
         COUNT(*) FILTER (WHERE p."kind" = 'AUDIO_MASTER'),
         COUNT(*) FILTER (WHERE p."kind" = 'COVER_IMAGE'),
         COUNT(*) FILTER (
           WHERE m."processingStatus" = 'READY'
             AND m."checksumSha256" IS NOT NULL
             AND p."readinessChecksum" = m."checksumSha256"
             AND p."verifiedReadyAt" <= publication_time
         )
    INTO link_count, audio_count, cover_count, ready_count
    FROM public."PublicationMediaAsset" p
    JOIN public."MediaAsset" m
      ON m."id" = p."mediaAssetId"
     AND m."audioContentId" = p."audioContentId"
     AND m."kind" = p."kind"
     AND m."version" = p."mediaAssetVersion"
    WHERE p."publicationId" = publication_id;

  IF link_count <> 2 OR audio_count <> 1 OR cover_count <> 1 OR ready_count <> 2 THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ContentPublication requires exactly one timely verified READY AUDIO_MASTER and COVER_IMAGE with matching checksums';
  END IF;
END;
$$;

CREATE FUNCTION public.kora_check_publication_from_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM public.kora_assert_publication_ready(
    to_jsonb(NEW) ->> CASE WHEN TG_TABLE_NAME = 'ContentPublication' THEN 'id' ELSE 'publicationId' END
  );
  RETURN NULL;
END;
$$;

CREATE FUNCTION public.kora_check_publications_for_media_asset()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  linked_publication_id TEXT;
BEGIN
  FOR linked_publication_id IN
    SELECT "publicationId" FROM public."PublicationMediaAsset" WHERE "mediaAssetId" = NEW."id"
  LOOP
    PERFORM public.kora_assert_publication_ready(linked_publication_id);
  END LOOP;
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "ContentPublication_ready_media"
  AFTER INSERT OR UPDATE ON "ContentPublication"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_publication_from_row();
CREATE CONSTRAINT TRIGGER "PublicationMediaAsset_ready_media"
  AFTER INSERT ON "PublicationMediaAsset"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_publication_from_row();
CREATE CONSTRAINT TRIGGER "MediaAsset_preserve_publication_readiness"
  AFTER UPDATE ON "MediaAsset"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_publications_for_media_asset();

-- A ledger group is not valid until it has at least one strictly-positive
-- debit and credit and both totals are equal. The check runs at transaction end.
CREATE FUNCTION public.kora_assert_ledger_group_balanced(group_id TEXT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  debit_count BIGINT;
  credit_count BIGINT;
  debit_total BIGINT;
  credit_total BIGINT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public."LedgerTransactionGroup" WHERE "id" = group_id) THEN
    RETURN;
  END IF;

  SELECT COUNT(*) FILTER (WHERE "direction" = 'DEBIT'),
         COUNT(*) FILTER (WHERE "direction" = 'CREDIT'),
         COALESCE(SUM("amountCfa") FILTER (WHERE "direction" = 'DEBIT'), 0),
         COALESCE(SUM("amountCfa") FILTER (WHERE "direction" = 'CREDIT'), 0)
    INTO debit_count, credit_count, debit_total, credit_total
    FROM public."LedgerPosting"
    WHERE "groupId" = group_id;

  IF debit_count = 0 OR credit_count = 0 OR debit_total <> credit_total THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'LedgerTransactionGroup requires equal non-empty DEBIT and CREDIT totals';
  END IF;
END;
$$;

CREATE FUNCTION public.kora_check_ledger_group_from_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM public.kora_assert_ledger_group_balanced(
    to_jsonb(NEW) ->> CASE WHEN TG_TABLE_NAME = 'LedgerTransactionGroup' THEN 'id' ELSE 'groupId' END
  );
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "LedgerTransactionGroup_balanced"
  AFTER INSERT ON "LedgerTransactionGroup"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_ledger_group_from_row();
CREATE CONSTRAINT TRIGGER "LedgerPosting_balances_group"
  AFTER INSERT ON "LedgerPosting"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_ledger_group_from_row();

-- Each earning freezes the exact priced OrderItem gross amount, the artist
-- rate effective at insertion, the allocation policy and reconciliation time.
CREATE FUNCTION public.kora_validate_artist_earning_source()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  expected_gross BIGINT;
  expected_rate INTEGER;
  expected_policy "ArtistEarningAllocationPolicy";
  settlement_reconciled_at TIMESTAMP(3);
BEGIN
  SELECT oi."unitPriceCfa"::BIGINT * oi."quantity"::BIGINT,
         a."artistRevenueShareBps",
         ars."allocationPolicy",
         s."reconciledAt"
    INTO expected_gross, expected_rate, expected_policy, settlement_reconciled_at
    FROM public."OrderItem" oi
    JOIN public."AudioContent" ac
      ON ac."id" = NEW."audioContentId" AND ac."artistId" = NEW."artistId"
    JOIN public."Artist" a ON a."id" = ac."artistId"
    JOIN public."ArtistSettlement" ars
      ON ars."id" = NEW."artistSettlementId"
     AND ars."settlementId" = NEW."settlementId"
     AND ars."orderId" = NEW."orderId"
     AND ars."artistId" = NEW."artistId"
    JOIN public."Settlement" s
      ON s."id" = ars."settlementId" AND s."orderId" = ars."orderId"
    WHERE oi."id" = NEW."orderItemId"
      AND oi."orderId" = NEW."orderId"
      AND oi."audioContentId" = NEW."audioContentId"
    FOR SHARE OF a;

  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ArtistEarning source relations must identify one priced OrderItem and ArtistSettlement';
  END IF;
  IF NEW."grossItemAmountCfa"::BIGINT <> expected_gross THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ArtistEarning gross amount must equal its priced OrderItem';
  END IF;
  IF NEW."artistRevenueShareBps" <> expected_rate
     OR NEW."allocationPolicy" <> expected_policy
     OR NEW."createdAt" < settlement_reconciled_at THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ArtistEarning frozen rate, policy and creation time must match its reconciled source';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER "ArtistEarning_source_consistency"
  BEFORE INSERT ON "ArtistEarning"
  FOR EACH ROW EXECUTE FUNCTION public.kora_validate_artist_earning_source();

-- Artist allocation aggregates are checked after all immutable earning rows
-- have been inserted. Row-local arithmetic is covered by CHECK constraints.
CREATE FUNCTION public.kora_assert_artist_settlement(artist_settlement_id TEXT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  earning_count BIGINT;
  earning_sum NUMERIC;
  stored_sum BIGINT;
BEGIN
  SELECT "exactEarningsNumerator" INTO stored_sum
    FROM public."ArtistSettlement" WHERE "id" = artist_settlement_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT COUNT(*), COALESCE(SUM("exactEarningNumerator"::NUMERIC), 0)
    INTO earning_count, earning_sum
    FROM public."ArtistEarning"
    WHERE "artistSettlementId" = artist_settlement_id;

  IF earning_count = 0 OR earning_sum <> stored_sum::NUMERIC THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'ArtistSettlement exact earnings must equal its immutable ArtistEarning rows';
  END IF;
END;
$$;

CREATE FUNCTION public.kora_check_artist_settlement_from_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM public.kora_assert_artist_settlement(
    to_jsonb(NEW) ->> CASE WHEN TG_TABLE_NAME = 'ArtistSettlement' THEN 'id' ELSE 'artistSettlementId' END
  );
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "ArtistSettlement_exact_earnings"
  AFTER INSERT ON "ArtistSettlement"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_artist_settlement_from_row();
CREATE CONSTRAINT TRIGGER "ArtistEarning_exact_artist_settlement"
  AFTER INSERT ON "ArtistEarning"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_artist_settlement_from_row();

CREATE FUNCTION public.kora_assert_settlement_artist_total(settlement_id TEXT)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  allocation_count BIGINT;
  allocation_total BIGINT;
  earning_count BIGINT;
  earning_basis_total BIGINT;
  stored_total INTEGER;
  stored_basis INTEGER;
BEGIN
  SELECT "artistPayableAmountCfa", "distributableBasisCfa"
    INTO stored_total, stored_basis
    FROM public."Settlement" WHERE "id" = settlement_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT COUNT(*), COALESCE(SUM("payableAmountCfa"::BIGINT), 0)
    INTO allocation_count, allocation_total
    FROM public."ArtistSettlement"
    WHERE "settlementId" = settlement_id;

  IF allocation_count = 0 OR allocation_total <> stored_total::BIGINT THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Settlement artist payable must equal its ArtistSettlement allocations';
  END IF;

  SELECT COUNT(*), COALESCE(SUM("frozenBasisCfa"::BIGINT), 0)
    INTO earning_count, earning_basis_total
    FROM public."ArtistEarning"
    WHERE "settlementId" = settlement_id;

  IF earning_count = 0 OR earning_basis_total <> stored_basis::BIGINT THEN
    RAISE EXCEPTION USING ERRCODE = '23514', MESSAGE = 'Settlement distributable basis must equal its immutable ArtistEarning bases';
  END IF;
END;
$$;

CREATE FUNCTION public.kora_check_settlement_artist_total_from_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  PERFORM public.kora_assert_settlement_artist_total(
    to_jsonb(NEW) ->> CASE WHEN TG_TABLE_NAME = 'Settlement' THEN 'id' ELSE 'settlementId' END
  );
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER "Settlement_artist_total"
  AFTER INSERT ON "Settlement"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_settlement_artist_total_from_row();
CREATE CONSTRAINT TRIGGER "ArtistSettlement_settlement_artist_total"
  AFTER INSERT ON "ArtistSettlement"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_settlement_artist_total_from_row();
CREATE CONSTRAINT TRIGGER "ArtistEarning_settlement_artist_total"
  AFTER INSERT ON "ArtistEarning"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.kora_check_settlement_artist_total_from_row();
